### ISSUE TITLE
Assets not being loaded

### ISSUE THREAD

**Issue by farezv** [brianmaierjr/long-haul#1]
Hi, 

I'm trying to switch themes to long-haul and I've encountered a strange issue, where jekyll serves the blog up fine from my existing posts but doesn't seem to load any assets.

I get `Failed to load resource 404s` for the following assets.

```
http://farez.ca/assets/css/style.css
http://farez.ca/assets/js/modernizr.custom.15390.js 
http://farez.ca/assets/js/scripts.js 
http://farez.ca/assets/js/responsive-nav.min.js 
http://farez.ca/assets/js/dropcap.min.js 
http://farez.ca/assets/css/style.css
```

I'm not sure if this is related but I can't seem to run `compass watch` successfully. I get 

```
farez$ compass watch
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
LoadError on line ["179"] of /Users/farez/.rvm/gems/ruby-2.0.0-p481/gems/compass-core-1.0.3/lib/compass/configuration/data.rb: cannot load such file -- normalize-scss
```

Any idea what's wrong? I'm not a ruby or front-end programmer and have no experience with SASS etc.

Thank you for making long-haul, it's a great theme!

Farez

**Comment by brianmaierjr** [comment]
Hey @farezv,

Can you replicate this problem so that I can properly trouble shoot the assets not loading?

I'm going to assume that you have compass installed and all you should have to do is install the normalize-scss for the second problem like so:

```
$ gem install compass-normalize
```
