### ISSUE TITLE
Error when running compass watch

### ISSUE THREAD

**Issue by tonyynot** [brianmaierjr/long-haul#10]
When running <code>compass watch</code> I am receiving the following error:

<code>LoadError on line ["54"] of /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb: cannot load such file -- normalize-scss
Run with --trace to see the full backtrace</code>

I tried commenting out <code>require "normalize-scss"</code> on config.rb but this leads to another series of errors with Susy imports.

**Comment by andrevvalle** [comment]
how you solved? @tonyynot

**Comment by andrevvalle** [comment]
I had to install two dependencies "gem install susy" and "gem install normalize-scss" :laughing:

**Comment by brianmaierjr** [comment]
I spaced on this... I'll make sure to add this to the README doc.
