### ISSUE TITLE
tables in dark theme unreadable

### ISSUE THREAD

**Issue by accounting101** [brianmaierjr/long-haul#100]
the table header and even numbered rows are not visible because font is white with white background. I added the below in the dark theme portion in style.css
 tr:nth-child(2n) {
    background-color: gray;
  }
  th {
    background-color: gray;
  }

**Comment by brianmaierjr** [comment]
Resolved with https://github.com/brianmaierjr/long-haul/commit/19beec5792396707228f45413ae9431088eda8e6

Can be seen live at https://long-haul.netlify.app/blog/example-post-formatting/

Thanks for the suggestion @accounting101 !
