### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by mots** [brianmaierjr/long-haul#104]
Hi there!
This doesn't seem to build for me, neither on netlify, nor locally with the instructions from the README. There's a whole bunch of deprecation warnings, I'm guessing they might be related? Is this theme still supported?

https://gist.github.com/mots/bddec064d0bcf7786a430262989f21b3

**Comment by brianmaierjr** [comment]
@mots working on this. sorry about the delay

**Comment by brianmaierjr** [comment]
@mots Check out the latest release and see if that helps you get up and running.
