### ISSUE TITLE
Assets aren't loading

### ISSUE THREAD

**Issue by sebastianbarfort** [brianmaierjr/long-haul#11]
Hi Brian, 
thanks for a great template. 

I can't seem to get the assets to load when I push my site to gh-pages. It works fine when working locally. Would you mind taking a look? The site is at: 
https://github.com/sebastianbarfort/BoT
It renders at 
https://sebastianbarfort.github.io/BoT/

I'm sorry if this is a replica of #1, but I couldn't figure out what the problem was. 

Best, 
Sebastian

**Comment by brianmaierjr** [comment]
Hey Sebastian,

I think if you change the `baseurl` in `_config.yml` to `/BoT` instead of being blank it will fix your problem.

**Comment by sebastianbarfort** [comment]
That doesn't work. If you look at the source of the rendered page it still points to `/assets/css/style.css`. Have I specified the url wrong (should I remove `/BoT`?) or am I doing something else wrong?

**Comment by brianmaierjr** [comment]
I know this is going to sound weird but try putting that in quotes `/BoT`

**Comment by brianmaierjr** [comment]
Looks like things are loading now so I'm going to close this! Let me know if I can help with anything else.
