### ISSUE TITLE
Liquid Syntax Error

### ISSUE THREAD

**Issue by chrisdemars** [brianmaierjr/long-haul#12]
When running ```jekyll serve``` I get this error:

 ```
Liquid Exception: Liquid syntax error: Unexpected character \ in "{{ \'/assets/js/jquery-1.11.2.min.js\' | prepend: site.baseurl }}" in _includes/scripts.html, included in _layouts/default.html
jekyll 3.0.0.pre.beta4 | Error:  Liquid syntax error: Unexpected character \ in "{{ \'/assets/js/jquery-1.11.2.min.js\' | prepend: site.baseurl }}"
```
I am not sure if this is something I need to fix on my end. This is my second attempy at using a Jekyll theme are yours is awesome but very complex lol. Also, I do get this error as well even after I install the gem.

```
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
```
Any help you have would be great. Like I said, your theme is dope and I can't wait to use it. Thanks!

**Comment by brianmaierjr** [comment]
I believe it's because of the Jekyll version you using. Can you try using an older version and see if that fixes things?

**Comment by chrisdemars** [comment]
I will check that out and get back with you. Thanks Brian!

**Comment by brianmaierjr** [comment]
Any luck @chrisdemars ?

**Comment by chrisdemars** [comment]
I haven't even tried yet Brian lol. I did however downgrade my version of
Jekyll so I have to see if that indeed did work. Been busy with graduation
and finishing up last minute class projects.

Once I take a look I will surely let you know! Thanks for the support.
