### ISSUE TITLE
Not been able to update colors

### ISSUE THREAD

**Issue by danielgomezrico** [brianmaierjr/long-haul#19]
Hi

Thanks for a great template and I´m trying to update the colors.
I´m changing the file `assets/scss/_config.scss`
```
// Color variables
$primary-color: $mat_indigo_500;
$secondary-color: $mat_indigo_500;
$tertiary-color: $mat_indigo_900;
$link-color: $primary-color;

$bad-color: $red; // Bad color for errors, validation etc.
$good-color: $primary-color; // Good color for success etc.
$info-color: $blue; // Good color for success etc.
$warning-color: $orange; // Good color for success etc.
$subtle-color: $grey; // Subtle color for subtle text
````

But nothing happens. why?

**Comment by brianmaierjr** [comment]
Hello,

Make sure you follow the instructions in the readme document and most notably have compass running to watch your sass files for changes.

**Comment by danielgomezrico** [comment]
I tried running:

```
# jekyll build
# jekyll serve
```

and 

```
# jekyll serve -w
```

but still not works.

**Comment by brianmaierjr** [comment]
Install susy `gem install susy`
Install normalize `gem install normalize-scss`
Run Jekyll `jekyll serve -w`
In a new window/tab run `compass watch`
Customize!

**Comment by danielgomezrico** [comment]
And it worked! :+1:

**Comment by brianmaierjr** [comment]
Great! Have fun and please share your site after it's up.

**Comment by danielgomezrico** [comment]
http://www.makingiants.com :)
