### ISSUE TITLE
Creating new footer icons

### ISSUE THREAD

**Issue by pedrorijo91** [brianmaierjr/long-haul#2]
I was trying to create new footer icons (hacker news, feeds, and linkedin for example) and I can't understand how are you doing them...

**Comment by brianmaierjr** [comment]
Hey @pedrorijo91,

Other icons can be found here http://customizr.net/icons?preset=f7f7f7-100-50-2e8b57-100-30-c-f1f1f1-100

Download the svg versions and copy + paste code as needed into `footer.html`

**Comment by pedrorijo91** [comment]
Thanks @brianmaierjr !  Really awesome. Nevertheless I've noticed that there is no icon for hacker news profile in this set. Could it be available somewhere else?

**Comment by brianmaierjr** [comment]
Try this http://www.flaticon.com/search/hacker-news

This requires extra styling but that's the fun part!

**Comment by pedrorijo91** [comment]
Let the fun begin ! :)

**Comment by mortymacs** [comment]
Hi :)

I just checked the website  http://customizr.net/icons?preset=f7f7f7-100-50-2e8b57-100-30-c-f1f1f1-100 but it can't be loaded.
Do you have any alternative websites which give SVG Icons for free without any licenses?

Thanks.
