### ISSUE TITLE
double bullet indentions are too wide

### ISSUE THREAD

**Issue by aav7fl** [brianmaierjr/long-haul#21]
Whenever I make a bulleted list that has sub bullets, the indention is insanely far to the point where listed item starts on the halfway point of the page.

![kvwz46b](https://cloud.githubusercontent.com/assets/3487107/9700401/60518f96-53cf-11e5-918d-b89edb412455.png)

**Comment by brianmaierjr** [comment]
Thanks! I'll take a look in to this.

**Comment by aav7fl** [comment]
Thank you!

**Comment by brianmaierjr** [comment]
Just pushed this. Thanks for noticing!

**Comment by aav7fl** [comment]
Thank you for fixing this! I tried but was unable to. I'll take a look now to see how you did it.
