### ISSUE TITLE
Having problems running the project

### ISSUE THREAD

**Issue by ivosantiago** [brianmaierjr/long-haul#25]
Hey @brianmaierjr 

Thanks for the awesome theme! I'm pretty new to jekyll (I might be doing something wrong) but when I tried to build the project following your steps I got this error:
```
Configuration file: <my-path>/long-haul/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: <my-path>/long-haul
       Destination: <my-path>/long-haul/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Dependency Error: Yikes! It looks like you don't have redcarpet or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- redcarpet' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 
  Conversion error: Jekyll::Converters::Markdown encountered an error while converting '_posts/2014-12-10-test-post.markdown':
                    redcarpet
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    redcarpet
```

I did try to install the pygments gem ( `gem install pygments.rb` ) as some people online said it would resolve this kind of problem but it didn't fix it for me. Any idea what is going on?

Don't know what kind of extra information you might need to check this problem but please let me know if I can do something to help.

Thanks a lot again

**Comment by brianmaierjr** [comment]
Did you also install the jekyll-paginate gem as mentioned above? You could possibly try another syntax highlighting and see if that works.

**Comment by ivosantiago** [comment]
I did and it still not working. :disappointed: 

I don't understand jekyll yet but do you have any suggestions for another syntax highlighting.

**Comment by brianmaierjr** [comment]
The default highlighter is now Rouge so maybe you could try that?

https://jekyllrb.com/news/2015/10/26/jekyll-3-0-released/

**Comment by brianmaierjr** [comment]
To fix this you need to add `gems: [jekyll-paginate]` to the config.yml

**Comment by liamwilley** [comment]
I am having a similar error, Dependency Error: Yikes! It looks like you don't have jekyll-paginate or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- jekyll-paginate' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 

but I do not quite understand where you are talking about adding the paginate gem in _config.yml since It is not a directory.

**Comment by liamwilley** [comment]
actually upon further investigation, gems: [jekyll-paginate] is in the file already. so now i really am not sure what to do.
