### ISSUE TITLE
How to change the style of inline syntax?

### ISSUE THREAD

**Issue by karagawa** [brianmaierjr/long-haul#33]
Hi, brian:

I am a newbie of jekyll, but I really like the long-haul theme. I am building my website based on it. When I try to use the  `` (single quote) to highlight words or syntax inline, I find it not obvious enough to see this in-line highlighting. Could you let me know where is the source code for inline syntax that I can modify? 

Also, I am wondering whether the theme where box for syntax highlighting is wider than normal paragraph is kind of style you try to keep in the theme? How can I modify the size of the syntax box? Thank you!

**Comment by brianmaierjr** [comment]
Hey @karagawa,

Everything can be found within the `scss` folder. You must have compass watching the files to make sure they are compiled. Hope this helps.
