### ISSUE TITLE
markdown grammar of quote use failed

### ISSUE THREAD

**Issue by Linkding** [brianmaierjr/long-haul#39]
when use markdown grammar about 「quote」

i read about the 《Example Post Formatting》

```
<blockquote>***</blockquote>
```

but,it didn't work

look like this:

![2016-08-02 16 16 20](https://cloud.githubusercontent.com/assets/13794365/17321715/974b2662-58cc-11e6-8727-a38a76b0f8e1.jpg)

i wrote by this:

![2016-08-02 16 16 35](https://cloud.githubusercontent.com/assets/13794365/17321736/aae91c9c-58cc-11e6-9c80-9a8dd686033f.jpg)

**Comment by brianmaierjr** [comment]
Are you saying that the blockquote did not work when using markdown?

**Comment by aochuih** [comment]
Do you mean that the current backquote's style is not you expected?
If yes, you need to custom the style in '_mobileup.scss' file.

==backquote== 's styles are defined in '_mobileup.scss', 
<img width="947" alt="backquote" src="https://cloud.githubusercontent.com/assets/4971341/17441913/de25c4ca-5b65-11e6-8eb8-1c13925c24b7.png">
