### ISSUE TITLE
Home tab isn't marked as current

### ISSUE THREAD

**Issue by dbryla** [brianmaierjr/long-haul#40]
Hello, I've a problem with nav bar. After I downloaded and launched page, behaviour of nav bar is inconsistent with the one from demo. First tab isn't highlighted and on demo it works. Do you have any idea why is that?

I've tried to debug this, but I don't have any idea how it works in demo, because page.url of home is always - baseUrl/ and link.url is /index.html, so page.url contains link.url is always false.

Quick fix is to extend condition in header.html to:

> if page.url contains link.url or forloop.first and page.url == '/'

I can create for that PR, but I am not happy with that solution.

**Comment by brianmaierjr** [comment]
Off the top of my head I am not sure. I will take a look at this soon.

**Comment by brianmaierjr** [comment]
I have implemented your fix and additionally have it checked to see if it's on `index.html` 

Thanks for sending this over!
