### ISSUE TITLE
compass errors

### ISSUE THREAD

**Issue by ggio** [brianmaierjr/long-haul#42]
Compass is detaching the header image from the corners when I `bundle exec compass watch`:

![printscreen](https://cloud.githubusercontent.com/assets/15349868/19889292/465625b8-a01b-11e6-855c-4a8744c6dd8f.png)

I'm also receiving those warnings:
 
> "DEPRECATION WARNING on line 87 of /var/lib/gems/2.1.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} 
> (...)
> DEPRECATION WARNING on line 92 of /var/lib/gems/2.1.0/gems/compass-core-1.0.3/stylesheets/compass/css3/_deprecated-support.scss: #{} 
> (...)"

I pinned the sass version to 3.4.16 in Gemfile and the warnings were gone, but the header malfunctions persisted.

**Comment by brianmaierjr** [comment]
Is there a live example I can look at?

**Comment by ggio** [comment]
yep: http://gregs.blog.br/long-haul/

**Comment by brianmaierjr** [comment]
I added some css to the body to fix the margin issue. Let me know if it is still happening.
