### ISSUE TITLE
Diagonal shape in big screens

### ISSUE THREAD

**Issue by ggio** [brianmaierjr/long-haul#44]
The diagonal shape on header's image seems buggy in big screens and small zoom.

![captura de tela de 2016-11-08 10 22 01](https://cloud.githubusercontent.com/assets/15349868/20098965/6adb48d2-a59d-11e6-9c18-f0ce34394995.png)

**Comment by brianmaierjr** [comment]
Bumped the size of the after element so that this wouldn't happen at larger sizes!
