### ISSUE TITLE
[Feature Request] Add global color option to config

### ISSUE THREAD

**Issue by aav7fl** [brianmaierjr/long-haul#5]
Hello there! I was taking a look at this theme for usage with Jekyll. I'm really liking it! I was wondering if I could request a small feature. I see that most of the green elements in the CSS are the same color. Would you be able to add in a config option to change this color globally instead of changing each instance in the stylesheet?

**Comment by brianmaierjr** [comment]
Hey @aav7fl,

If you change the `$primary-color` variable in `_config.scss` and that should take care of most things. Hope that helps.

**Comment by aav7fl** [comment]
Thanks! I must have missed that.

**Comment by aav7fl** [comment]
When I tried changing that variable, none of the colors that should change do.. or any that I can view. The stylesheet does get updated, but it still contains lots of seagreen.

**Comment by brianmaierjr** [comment]
Thanks for getting back on that! I'll replace all the `seagreen` with `$primary-color` in the near future. If you do a global find and replace that should fix the problem for you.

**Comment by aav7fl** [comment]
Thanks!  I will do that. I just wanted to bring that to your attention.

**Comment by EmilBuszylo** [comment]
Hi I have changed `seagreen` in `_config.scss` file to `$orange` (second try with `orange`) and color of links (via `$link-color: $primary-color;`) are still green - not orange as I have expected. What am I doing wrong?

**Comment by brianmaierjr** [comment]
A couple thoughts.

We're you watching the scss files so they would be compiled?

Did you declare $orange previously? You could take off the dollar sign and use the code color name if you wanted.

Brian Maier Jr.
Web Designer & Developer
brianmaierjr.com (http://www.brianmaierjr.com)
@brianmaierjr (http://www.twitter.com/brianmaierjr)
