### ISSUE TITLE
How to get Pagination on a page other than the Homepage?

### ISSUE THREAD

**Issue by DanielRoberts95** [brianmaierjr/long-haul#6]
I wanted my site to have the About page featured on the homepage, and my Recent Posts featured on a Blog page. I was able to make this work by doing the following.

I took the code that was originally in the index.html and pasted it into a blog.md file in the root directory. At first, nothing showed up on the page, but when I changed the line:

{% for post in paginator.posts %}

to:

{% for post in site.posts %}

all of my blog posts appeared on the Blog page. The only problem is that there is no pagination on the page. Any help would be greatly appreciated, thank you :)

**Comment by brianmaierjr** [comment]
Hey @DanielRoberts95,

Check out this page http://jekyllrb.com/docs/pagination/ it should have all your answers.

**Comment by DanielRoberts95** [comment]
Hi @brianmaierjr 

I've looked over the documentation but I haven't had any luck with it. Are you sure that pagination works properly on pages other than index.html? I'm wondering because @kleinfreund said [here](https://github.com/jekyll/jekyll-help/issues/177) that pagination only works in index.html files. Thank you.

**Comment by brianmaierjr** [comment]
I haven't tried anywhere else..... Does that mean we can solve the problem by having a blog folder with an `index.html` file inside?

**Comment by DanielRoberts95** [comment]
It worked! Thank you so much!

Now I've got another problem though. When I'm in my blog page in the navigation it underlines both the Blog and Home links. Here's an image of what I'm talking about.
![rsz_bloghome](https://cloud.githubusercontent.com/assets/11403206/7127200/7d694796-e1f5-11e4-8bfc-14524269f8ac.png)

**Comment by brianmaierjr** [comment]
The nav code can be found in the `head.html`

I think the answer could be here but it will take some experimenting http://stackoverflow.com/questions/8340170/jekyll-automatically-highlight-current-tab-in-menu-bar

I hope that helps.
