### ISSUE TITLE
Changing the title

### ISSUE THREAD

**Issue by skinnylatte** [brianmaierjr/long-haul#61]
Hi Brian, great theme. First one I have liked in a while.

I use your theme on http://popagandhi.com/ and I have changed the title in my config file. However, it still outputs as Long Haul. Do you know where I can change it?

**Comment by brianmaierjr** [comment]
I believe you want to change it in the `index.html` file

**Comment by skinnylatte** [comment]
Doh. Probably shouldn't do this at 4am.. :)
