### ISSUE TITLE
Twitter Cards Support

### ISSUE THREAD

**Issue by mustafa01ali** [brianmaierjr/long-haul#62]
Great job on the theme! Can you add support for [Twitter Cards](https://dev.twitter.com/cards/overview)? Currently, if you post a URL on Twitter, it doesn't display the feature image or the summary.

**Comment by brianmaierjr** [comment]
This is all setup. If a post uses a featured image then it will be used otherwise it will use a default image. The same goes for the description/summary, If you specify in the post it will be used.
