### ISSUE TITLE
 Could not find addressable-2.5.1 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by jenniejj** [brianmaierjr/long-haul#63]
I'm getting:

`WARN: Unresolved specs during Gem::Specification.reset:
      listen (< 3.1, ~> 3.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/spec_set.rb:88:in `block in materialize': Could not find addressable-2.5.1 in any of the sources (Bundler::GemNotFound)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/spec_set.rb:82:in `map!'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/spec_set.rb:82:in `materialize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/definition.rb:171:in `specs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/definition.rb:238:in `specs_for'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/definition.rb:227:in `requested_specs'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:110:in `block in definition_method'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler/runtime.rb:22:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.16.0.pre.2/lib/bundler.rb:107:in `setup'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/lib/jekyll/plugin_manager.rb:48:in `require_from_bundler'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/jekyll-3.5.2/exe/jekyll:9:in `<top (required)>'
        from C:/Ruby24-x64/bin/jekyll:23:in `load'
        from C:/Ruby24-x64/bin/jekyll:23:in `<main>'`

after running `jekyll serve`

**Comment by jenniejj** [comment]
I have also tried to apply this theme without using the gems just by copying the theme into my website's folder and then tried to run jekyll serve and I'm getting this:

```
Configuration file: none
            Source: C:/womensportcamp.com
       Destination: C:/womensportcamp.com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
jekyll 3.6.0 | Error:  No such file or directory @ rb_sysopen - C:/womensportcamp.com/womensportcamp.com-Files/twisterTheme/twister_theme/node_modules/grunt-contrib-imagem
in/node_modules/imagemin/node_modules/imagemin-svgo/node_modules/svgo/node_modules/js-yaml/node_modules/argparse/node_modules/underscore/underscore-min.js
```
Not sure who and why is it looking for the underscore-min.js

**Comment by brianmaierjr** [comment]
If you are current with the theme we now use gulp to serve the site and watch files.
