### ISSUE TITLE
og:image is not worked

### ISSUE THREAD

**Issue by Griiid** [brianmaierjr/long-haul#64]
Hi, thanks for your beautiful and easy to use jekyll template!

I added Open Graph meta to my blog today and I noticed that your template has a bug that the `og:image` won't display!

in `_includes/head.html`, the code below has something wrong:

```
<meta content="{{ '/assets/img/touring.jpg' | prepend: site.baseurl }}" property="og:image">
```

In `_config.yml`, `site.baseurl` is empty so that the code above will become 

```
<meta content="'/assets/img/touring.jpg" property="og:image">
```

I've tried myself to replace `site.baseurl` with `site.url` and it works, maybe you can fix it?

```
<meta content="{{ '/assets/img/touring.jpg' | prepend: site.url }}" property="og:image">
```

**Comment by brianmaierjr** [comment]
Made the changes, thank you!
