### ISSUE TITLE
Outdated npm packages

### ISSUE THREAD

**Issue by davrandom** [brianmaierjr/long-haul#73]
Hi Brian,

I decided to come and see if you updated the theme in the last years and it looks so!
You adopted some new things I'm getting familiar right now.

Going to the point, running 
```
npm install
```
I get some warnings:
```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```
what's the best thing to do?

Thanks

**Comment by brianmaierjr** [comment]
Hey @davrandom, 

From what I'm seeing you can ignore those warnings. I made some general updates and everything seems to be working well if you want to pull those changes. Here are the last two commits:

https://github.com/brianmaierjr/long-haul/commit/407173ca0fbe3c846031defdf2003e2ce557f266
https://github.com/brianmaierjr/long-haul/commit/7254fde33215d88bcd39161e025cb2a36ced2af3
