### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by alexandru** [brianmaierjr/long-haul#74]
This theme is super awesome.

Just one suggestion — would be nice to offer some guidance for extra features people might want, like integrating a commenting widget or displaying a "related articles" at the bottom at the page.

But I guess I can get my hands dirty and the typography, omg it's the best I've seen.

**Comment by brianmaierjr** [comment]
Thanks for the comment. I would absolutely like to extend this theme more when I get the time and your suggestions are great.
