### ISSUE TITLE
How to change color instead of green?

### ISSUE THREAD

**Issue by quockhai** [brianmaierjr/long-haul#76]
I want to chang primary color instead of green (seagreen?). How to do that?

**Comment by brianmaierjr** [comment]
The best way to do that is follow the setup instructions in the readme to get your local development environment ready and watching the files. Next you'll want to change seagreen to whatever color you want here https://github.com/brianmaierjr/long-haul/blob/407173ca0fbe3c846031defdf2003e2ce557f266/assets/scss/_config.scss#L28

This should compile all assets and reload the page so your new color is the primary color.

I hope that helps!
