### ISSUE TITLE
Problem getting theme working

### ISSUE THREAD

**Issue by molitona** [brianmaierjr/long-haul#98]
I've problem getting long-haul theme working as newer to jekyll.

I have installed jekyll, done npm install gulp, then typed jekyll new . in my blog dir.

![hhh](https://user-images.githubusercontent.com/35532337/122991660-3526e600-d39d-11eb-80ca-2fdc856493a8.png)

I cloned the repo into blog directory as you see above.

I run bundle exec gulp from blog/long-haul and got that :

> rror: Cannot find module 'browser-sync'
> Require stack:
> - /home/user/blog/long-haul/gulpfile.js
> - /home/user/node_modules/gulp-cli/lib/shared/require-or-import.js
> - /home/user/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js
> - /home/user/node_modules/gulp-cli/index.js
> - /home/user/node_modules/gulp/bin/gulp.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:774:27)
>     at Module.require (node:internal/modules/cjs/loader:1013:19)
>     at require (node:internal/modules/cjs/helpers:93:18)
>     at Object.<anonymous> (/home/user/blog/long-haul/gulpfile.js:2:19)
>     at Module._compile (node:internal/modules/cjs/loader:1109:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
>     at Module.load (node:internal/modules/cjs/loader:989:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:829:14)
>     at Module.require (node:internal/modules/cjs/loader:1013:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/user/blog/long-haul/gulpfile.js',
>     '/home/user/node_modules/gulp-cli/lib/shared/require-or-import.js',
>     '/home/user/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js',
>     '/home/user/node_modules/gulp-cli/index.js',
>     '/home/user/node_modules/gulp/bin/gulp.js'
>   ]
> }
> 
> 
> 

when I run jekyll serve from blog dir without the above command I get :

![jj](https://user-images.githubusercontent.com/35532337/122991638-2b9d7e00-d39d-11eb-8793-a1988e29d555.png)

How can I get your theme working! 
Thanks!

**Comment by molitona** [comment]
Hi, is there any response ?

**Comment by brianmaierjr** [comment]
Really sorry about the late response. My advice would be to start a new site and follow the instruction in the readme.
